/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Rojas Piña Efrain Ulises <al2172001457@azc.uam.mx>
 */
public class GUI_subirArchivos extends javax.swing.JFrame {

   /**
    * Creates new form GUI_subirArchivos
    */
   String rutaPA = "";
   String rutaFormato = "";
   String nombrePA = "";
   String nombreFormato = "";

   public GUI_subirArchivos() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      btnAnalizar = new javax.swing.JButton();
      btnSlectArchFormato = new javax.swing.JButton();
      btnSlectArchPA = new javax.swing.JButton();
      lblNomF = new javax.swing.JLabel();
      lblNomPA = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setText("APALizer");

      jLabel2.setText("Formato:");

      jLabel3.setText("Producto academico:");

      btnAnalizar.setText("Analizar");
      btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAnalizarActionPerformed(evt);
         }
      });

      btnSlectArchFormato.setText("Seleccionar Archivo");
      btnSlectArchFormato.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSlectArchFormatoActionPerformed(evt);
         }
      });

      btnSlectArchPA.setText("Seleccionar Archivo");
      btnSlectArchPA.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSlectArchPAActionPerformed(evt);
         }
      });

      lblNomF.setText("Seleccione un arhivo pdf o docx");

      lblNomPA.setText("Seleccione un arhivo pdf o docx");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(220, 220, 220)
                  .addComponent(jLabel1))
               .addGroup(layout.createSequentialGroup()
                  .addGap(64, 64, 64)
                  .addComponent(jLabel2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(lblNomF, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(203, 203, 203)
                  .addComponent(btnAnalizar))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(lblNomPA, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(14, 14, 14)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnSlectArchFormato)
               .addComponent(btnSlectArchPA))
            .addContainerGap(46, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addGap(27, 27, 27)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(btnSlectArchFormato)
               .addComponent(lblNomF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(34, 34, 34)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(btnSlectArchPA)
               .addComponent(lblNomPA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
            .addComponent(btnAnalizar)
            .addGap(60, 60, 60))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnSlectArchFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlectArchFormatoActionPerformed
      // TODO add your handling code here:
      //Creamos un JFileChooser para seleccion un archivo
      JFileChooser jFileChooser = new JFileChooser();
      //Creamos un filtro para que solo nos muestre archivos .pdf y .docx
      FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos pdf y docx", "pdf", "docx");
      //Le pasamos el filtro
      jFileChooser.setFileFilter(filter);

      int respuesta = jFileChooser.showOpenDialog(this);
      if (respuesta == JFileChooser.APPROVE_OPTION) {
         //Nombre del archivo
         nombreFormato = jFileChooser.getSelectedFile().getName();
         if (nombreFormato.lastIndexOf(".pdf") > 0 || nombreFormato.lastIndexOf(".docx") > 0) {
            //Ruta del archivo
            rutaFormato = jFileChooser.getSelectedFile().getPath();
            lblNomF.setText(nombreFormato);
         } else {
            nombreFormato = "";
            rutaFormato = "";
            lblNomF.setText("Seleccione un arhivo pdf o docx");
            JOptionPane.showMessageDialog(null, "Solo se permiten archivos pdf y docx");
         }
      }
   }//GEN-LAST:event_btnSlectArchFormatoActionPerformed

   private void btnSlectArchPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlectArchPAActionPerformed
      // TODO add your handling code here:
      //Creamos un JFileChooser para seleccion un archivo
      JFileChooser jFileChooser = new JFileChooser();
      //Creamos un filtro para que solo nos muestre archivos .pdf y .docx
      FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos pdf y docx", "pdf", "docx");
      //Le pasamos el filtro
      jFileChooser.setFileFilter(filter);

      int respuesta = jFileChooser.showOpenDialog(this);
      if (respuesta == JFileChooser.APPROVE_OPTION) {
         //Nombre del archivo
         nombrePA = jFileChooser.getSelectedFile().getName();
         if (nombrePA.lastIndexOf(".pdf") > 0 || nombrePA.lastIndexOf(".docx") > 0) {
            //Ruta del archivo
            rutaPA = jFileChooser.getSelectedFile().getPath();
            lblNomPA.setText(nombrePA);
         } else {
            nombrePA = "";
            rutaPA = "";
            lblNomF.setText("Seleccione un arhivo pdf o docx");
            JOptionPane.showMessageDialog(null, "Solo se permiten archivos pdf y docx");
         }
      }
   }//GEN-LAST:event_btnSlectArchPAActionPerformed

   private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
      // TODO add your handling code here:
      System.out.println("NF: " + nombreFormato + " " + "NPA: " + nombrePA);
      System.out.println("RF: " + rutaFormato + " " + "RPA: " + rutaPA);
      System.out.println("NF: " + nombreFormato.length() + " " + "NPA: " + nombrePA.length());
      if (nombreFormato.length() == 0 && nombrePA.length() == 0) {
         JOptionPane.showMessageDialog(null, "No se seleciono ningun archivo");
      } else if (nombreFormato.length() == 0) {
         JOptionPane.showMessageDialog(null, "No se seleciono el formato");
      } else if (nombrePA.length() == 0) {
         JOptionPane.showMessageDialog(null, "No se seleciono el producto academico");
      } else {
         GUI_DescargarArchivo dA = new GUI_DescargarArchivo();
         dA.setVisible(true);
         this.dispose();
         //JOptionPane.showMessageDialog(null, "Hola :D");
      }
   }//GEN-LAST:event_btnAnalizarActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(GUI_subirArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(GUI_subirArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(GUI_subirArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(GUI_subirArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new GUI_subirArchivos().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAnalizar;
   private javax.swing.JButton btnSlectArchFormato;
   private javax.swing.JButton btnSlectArchPA;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel lblNomF;
   private javax.swing.JLabel lblNomPA;
   // End of variables declaration//GEN-END:variables
}
